{
 "title": "📈 Monitorización de Flask - Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Peticiones por ruta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (\r\n  flask_http_request_duration_seconds_count{path!=\"/favicon.ico\"}\r\n)\r\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Tiempo medio de respuesta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{path=\"/hello\"}[1m])\r\n/\r\nrate(flask_http_request_duration_seconds_count{path=\"/hello\"}[1m])\r\n",
     "legendFormat": "/hello"
    },
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{path=\"/error\"}[1m])\r\n/\r\nrate(flask_http_request_duration_seconds_count{path=\"/error\"}[1m])\r\n",
     "legendFormat": "/error"
    }
   ]
  },
  {
   "title": "Peticiones HTTP por estado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"200\"}\r\n",
     "legendFormat": "Peticiones exitosas (200)"
    },
    {
     "expr": "flask_http_request_total{status=\"500\"}\r\n",
     "legendFormat": "Errores del servidor (500)"
    }
   ]
  }
 ]
}