apiVersion: v1
kind: Service
metadata:
  name: flask-otel-service
spec:
  type: NodePort
  selector:
    app: flask-otel
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
