apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.54
        ports:
        - containerPort: 16686  # UI
        - containerPort: 4318   # OTLP HTTP

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: http
      port: 16686
      targetPort: 16686
      nodePort: 30001
    - name: otlp
      port: 4318
      targetPort: 4318
