apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"

      filelog:
        include:
          - /var/log/flask/app.log
        start_at: beginning
        operators:
          - type: regex_parser
            regex: '^(?P<time>\S+ \S+) (?P<severity>\S+) (?P<message>.+)'
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%d %H:%M:%S,%L'

    processors:
      batch: {}

    exporters:
      otlphttp:
        endpoint: http://jaeger:4318

      loki:
        endpoint: http://loki:3100/loki/api/v1/push

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]

        logs:
          receivers: [filelog]
          processors: [batch]
          exporters: [loki]

